import 'dart:io';

Future<void> main(List<String> args) async {
  final result = await Process.run(Platform.resolvedExecutable, [
    'run',
    'melos',
    'list',
    '--mermaid',
  ]);
  if (result.exitCode != 0) {
    stderr.write(result.stderr);
    exitCode = result.exitCode;
    return;
  }
  final graph = (result.stdout as String).trim();
  if (!graph.contains('graph') && !graph.contains('flowchart')) {
    throw StateError('Melos did not return a Mermaid graph.');
  }
  final content =
      '# Module dependencies\n\nGenerated by `dart run melos run graph`. Do not edit manually. Arrows follow Melos dependency direction; this graph describes declared package dependencies, not runtime ownership.\n\n```mermaid\n$graph\n```\n';
  final output = File('docs/module-graph.md');
  if (args.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != content) {
      stderr.writeln(
        'Dependency graph is stale. Run dart run melos run graph.',
      );
      exitCode = 1;
    }
  } else {
    output.parent.createSync(recursive: true);
    output.writeAsStringSync(content);
    stdout.writeln('Updated ${output.path}');
  }
}
