arb-dir: lib/src/l10n
template-arb-file: note_review_en.arb
output-dir: lib/src/l10n/generated
output-localization-file: note_review_localizations.dart
output-class: NoteReviewLocalizations
nullable-getter: false
